image: openjdk:11

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew build
    - step:
        name: Deploy to test
        deployment: test
        script:
          - git fetch --unshallow origin
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/video-rental-store-test.git HEAD
